### ISSUE TITLE
Error in SO-NET code

### ISSUE THREAD

**Issue by dsd009** [lijx10/SO-Net#28]
Kindly resolve this issue.

I'm running the classification task but I get the following error:
system info:
python 3.7
pytorch 1.2
cuda 10.2
faiss toolkit for cuda 10
------------ Options -------------
activation: relu
batch_size: 8
bn_momentum: 0.1
bn_momentum_decay: 0.6
bn_momentum_decay_step: None
checkpoints_dir: ./checkpoints
classes: 40
dataroot: /home/raman/Reconstruction/modelnet40-normal_numpy/
dataset: modelnet
device: cpu
display_id: 200
display_winsize: 256
dropout: 0.7
feature_num: 1024
gpu_id: 0
input_pc_num: 5000
k: 3
lr: 0.001
nThreads: 8
name: train
node_num: 64
normalization: batch
pretrain: None
pretrain_lr_ratio: 1
random_pc_dropout_lower_limit: 1
rot_horizontal: False
rot_perturbation: False
som_k: 9
som_k_type: avg
surface_normal: True
translation_perturbation: False
-------------- End ----------------
Traceback (most recent call last):
File "train.py", line 20, in 
from models.classifier import Model
File "../models/classifier.py", line 11, in 
from . import networks
File "../models/networks.py", line 17, in 
import index_max
ImportError: /home/raman/anaconda3/lib/python3.7/site-packages/index_max-0.0.0-py3.7-linux-x86_64.egg/index_max.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singleton

**Comment by dsd009** [comment]
kindly reply urgently....

**Comment by lijx10** [comment]
I will investigate this today or tomorrow. Sorry I have been occupied with a lot of work recently.

**Comment by dsd009** [comment]
Kindly look at the issue. we are waiting for the problem to be solved at the earliest.

**Comment by vaibhavnayel** [comment]
I'm facing the same issue. is there a fix yet?

**Comment by dsd009** [comment]
does this code has any compatability issues with cuda10.1

**Comment by usherbob** [comment]
Downgrading torch version to 1.1 works for me. My env, python=3.7, torch=1.1, cuda=10.0.

**Comment by amiltonwong** [comment]
Hi, @usherbob,

My environment is configured with python 3.6, cuda 10.0, pytorch 1.1.0 and torchvision 0.3.0. However, I got the following ` operation not supported` error. Any suggestions to fix this issue?

```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=51 error=71 : operation not supported
Traceback (most recent call last):
  File "/data/code10/SO-Net/modelnet/train.py", line 32, in <module>
    model = Model(opt)
  File "/data/code10/SO-Net/models/classifier.py", line 40, in __init__
    self.encoder = self.encoder.to(self.opt.device)
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  [Previous line repeated 1 more times]
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (71) : operation not supported at /pytorch/aten/src/THC/THCGeneral.cpp:51

Process finished with exit code 1
```

THX~

**Comment by usherbob** [comment]
Hi, @amiltonwong, did you compile the index_max operation successfully?

**Comment by amiltonwong** [comment]
Hi, @usherbob , 

Yes, it is compiled successfully.

```
(pytorch1.1) root@milton-OptiPlex-9010:/data/code10/SO-Net/models/index_max_ext# python3 setup.py install
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running install
running bdist_egg
running egg_info
writing index_max.egg-info/PKG-INFO
writing dependency_links to index_max.egg-info/dependency_links.txt
writing top-level names to index_max.egg-info/top_level.txt
reading manifest file 'index_max.egg-info/SOURCES.txt'
writing manifest file 'index_max.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'index_max' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include/TH -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/pytorch1.1/include/python3.6m -c index_max.cpp -o build/temp.linux-x86_64-3.6/index_max.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=index_max -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include/TH -I/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/pytorch1.1/include/python3.6m -c index_max_cuda.cu -o build/temp.linux-x86_64-3.6/index_max_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=index_max -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -L/root/anaconda3/envs/pytorch1.1/lib -Wl,-rpath=/root/anaconda3/envs/pytorch1.1/lib,--no-as-needed -L/root/anaconda3/envs/pytorch1.1/lib -Wl,-rpath=/root/anaconda3/envs/pytorch1.1/lib,--no-as-needed build/temp.linux-x86_64-3.6/index_max.o build/temp.linux-x86_64-3.6/index_max_cuda.o -L/usr/local/cuda/lib64 -L/root/anaconda3/envs/pytorch1.1/lib -lcudart -lpython3.6m -o build/lib.linux-x86_64-3.6/index_max.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.6/index_max.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for index_max.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/index_max.py to index_max.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying index_max.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying index_max.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying index_max.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying index_max.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.index_max.cpython-36: module references __file__
creating dist
creating 'dist/index_max-0.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing index_max-0.0.0-py3.6-linux-x86_64.egg
creating /root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/index_max-0.0.0-py3.6-linux-x86_64.egg
Extracting index_max-0.0.0-py3.6-linux-x86_64.egg to /root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages
Adding index-max 0.0.0 to easy-install.pth file

Installed /root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/index_max-0.0.0-py3.6-linux-x86_64.egg
Processing dependencies for index-max==0.0.0
Finished processing dependencies for index-max==0.0.0

```

**Comment by usherbob** [comment]
Then I don't know the reason, sorry couldnot help.

**Comment by lijx10** [comment]
Please make sure that the cuda environment is configured properly. For example, proper environment variables. For example, you may consider adding these lines to `~/.bashrc`
```
# cuda-10.1
export CUDA_HOME=/usr/local/cuda-10.1
export PATH=/usr/local/cuda-10.1/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:${LD_LIBRARY_PATH}
```
Run `nvcc -V` to confirm that cuda is working properly.

After making sure that cuda and pytorch is installed properly, delete folder `dist`, `build`, and the file `index_max.egg-info`, then run `python setup install` to install the `index_max` module again.

Finally, please make sure that the `index_max` folder is not in the python path. There may be linking problems.

**Comment by dsd009** [comment]
Hi
I have issues with installing faiss after i installed cuda 10.1.  How can i
install it successfully.

**Comment by robin1chen2** [comment]
"Finally, please make sure that the index_max folder is not in the python path. There may be linking problems."
You said make sure that the index_max_ext folder ''is not", instead of ''is'' ,in the python path .Did you make a mistake or I misunderstood?
